version: '3'

services:
  sleek-airflow:
    image: i200658_a2:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8081
    command: airflow standalone
